Repository knative-extensions/eventing-kogito, pull requests merged in 2021-10, with the labels that each got.

#21 Reverting coc changes
  CODE-OF-CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: cla: yes, approved, lgtm, size/S

#24 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: cla: yes, approved, lgtm, size/XS

#28 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/apis/kogito/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/signals/signal_posix.go
  vendor/knative.dev/pkg/tracing/config/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M
