Repository knative-extensions/eventing-kogito, pull requests merged in 2022-06, with the labels that each got.

#150 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#146 [KOGITO-6602] Setup Eventing Kogito CI to integrate with OLM integrat…
  Makefile
  hack/ci/operator-ensure-manifests.sh
  hack/ci/run-olm-tests.sh
  hack/env.sh
  pkg/version/version.go
Labels: approved, lgtm, size/L, ok-to-test

#152 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#153 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#154 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#155 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  third_party/VENDOR-LICENSE/go.uber.org/multierr/LICENSE.txt
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/options.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_data.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_retry.go
  vendor/go.uber.org/multierr/.travis.yml
  vendor/go.uber.org/multierr/CHANGELOG.md
  vendor/go.uber.org/multierr/LICENSE.txt
  vendor/go.uber.org/multierr/Makefile
  vendor/go.uber.org/multierr/README.md
  vendor/go.uber.org/multierr/error.go
  vendor/go.uber.org/multierr/go.mod
  vendor/go.uber.org/multierr/go.sum
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/global.go
  vendor/go.uber.org/zap/global_go112.go
  vendor/go.uber.org/zap/global_prego112.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/level.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/stacktrace.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/level.go
  vendor/go.uber.org/zap/zapcore/reflected_encoder.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#156 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review
