Repository knative-extensions/eventing-kogito, pull requests merged in 2022-01, with the labels that each got.

#68 Corrected broken link
  README.md
Labels: approved, lgtm, size/XS, needs-ok-to-test

#69 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#71 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#72 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#73 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#74 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/klog/LICENSE
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/doc.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#75 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, lgtm, size/XS

#76 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#77 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#78 [KOGITO-6532] Enable OLM installation bundle
  .gitignore
  Makefile
  PROJECT
  bundle.Dockerfile
  bundle/manifests/config-logging_v1_configmap.yaml
  bundle/manifests/config-observability_v1_configmap.yaml
  bundle/manifests/eventing-kogito.clusterserviceversion.yaml
  bundle/manifests/kogito-source-controller-manager_v1_service.yaml
  bundle/manifests/kogito-source-observer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/kogito.knative.dev_kogitosources.yaml
  bundle/metadata/annotations.yaml
  bundle/metadata/dependencies.yaml
  bundle/tests/scorecard/config.yaml
  config/500-webhook-configuration.yaml
  config/olm/default/kustomization.yaml
  config/olm/manifests/bases/eventing-kogito.clusterserviceversion.yaml
  config/olm/manifests/bases/kogito_v1alpha1_kogitosource.yaml
  config/olm/manifests/csv-descriptors-patch.json
  config/olm/manifests/kustomization.yaml
  config/olm/rbac/addressable-resolvers-clusterrolebinding.yaml
  config/olm/scorecard/bases/config.yaml
  config/olm/scorecard/kustomization.yaml
  config/olm/scorecard/patches/basic.config.yaml
  config/olm/scorecard/patches/olm.config.yaml
  config/olm/webhooks/kustomization.yaml
  config/olm/webhooks/remove-admission-webhooks.yaml
  examples/README.md
  examples/kogito-source-order-processing-workflow.yaml
  pkg/apis/kogito/v1alpha1/kogitosource_types.go
Labels: kind/enhancement, approved, size/XXL, lgtm

#79 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#80 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#81 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#83 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, lgtm, size/XS

#84 [KOGITO-6482] Small adjustments for OLM release
  Makefile
  bundle/manifests/eventing-kogito.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/olm/installer/kustomization.yaml
  config/olm/installer/remove-admission-webhooks.yaml
  config/olm/manifests/bases/eventing-kogito.clusterserviceversion.yaml
  config/olm/manifests/csv-descriptors-patch.json
  config/olm/manifests/kustomization.yaml
  config/olm/rbac/addressable-resolvers-clusterrolebinding.yaml
Labels: kind/enhancement, approved, lgtm, size/M

#82 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#85 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
