Repository knative-extensions/eventing-kogito, pull requests merged in 2022-05, with the labels that each got.

#138 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#140 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#141 Fix broken links to Kogito examples
  README.md
Labels: approved, lgtm, size/XS, needs-ok-to-test, kind/documentation

#142 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#143 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#144 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#145 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#147 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#148 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M
