Repository knative-extensions/eventing-kogito, pull requests merged in 2022-02, with the labels that each got.

#86 Release Eventing Kogito 1.2.0 on OLM
  Makefile
  README.md
  bundle/manifests/eventing-kogito.clusterserviceversion.yaml
  bundle/manifests/kogito-source-controller-manager_v1_service.yaml
  bundle/manifests/kogito-source-observer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/kogito.knative.dev_kogitosources.yaml
  config/olm/installer/kustomization.yaml
  config/olm/manifests/bases/eventing-kogito.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#88 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#89 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: approved, lgtm, size/M

#90 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#91 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#92 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#93 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#94 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#95 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS

#96 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#97 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#98 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS

#99 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS

#100 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
