Repository knative-extensions/eventing-kogito, pull requests merged in 2023-04, with the labels that each got.

#238 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#242 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#240 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#244 chore: migrate from k8s.gcr.io to registry.k8s.io
  bundle/manifests/config-observability_v1_configmap.yaml
  config/config-observability.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#246 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#247 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#248 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
